### ISSUE TITLE
Sync-ContactList doesn't remove field from contacts detination if source field is emptied.

### ISSUE THREAD

**Issue by x-zempt** [grahamr975/EWS-Office365-Contact-Sync#31]
Hi there,
I've found an issue, say if John Smith has a phone number in his GAL in 'Business Phone' field. I pull that data into an array and push to users Contacts folders. Later John Smith stops having a work phone number and we empty the 'Business Phone' field from the GAL and do another sync. 
The current processing of Sync-ContactList doesn't replicate the empty field to the end users contacts when doing a sync.

Hope that makes sense.

**Comment by x-zempt** [comment]
No one else experienced this? Or an I doing something wrong. 
I think the logic is causing the issue.

Source field (GAL) for contact is empty/null (ie. phone numer), so do not sync/copy field. It doesn't seem to take into account that the destination (User contacts list) has data that is no longer relevant and to blank/null it out.

**Comment by grahamr975** [comment]
@x-zempt I see the issue you're talking about. In Set-EXCContactObject.ps1, contact fields are only updated if the data passed to each field isn't null/empty.
```
if ($FirstName -ne "" -And $FirstName -ne $null)
{
	$Contact.GivenName = $FirstName
}
```
I did this to prevent certain contact fields, such as notes, from being overwritten. This works in my environment since we've only changed cellphone numbers/names and not removed them, but I now see how this can cause problems in other environments.

To resolve this, I could set certain fields to allow null values, such as phone numbers, while leaving the notes field and others the same. What do you think?

**Comment by x-zempt** [comment]
Yea I can understand why you would do that.
Bug it doesn't sync the 'Notes' field of the contact etc anyway, as it isn't defined in the PS script to sync. Isn't that correct?

I think what would be handy is if we define the fields we want to sync as true/false flag when running the script.

Also, would be handy to define a email domain for which email accounts to remove from the users email box (ie. the company/business domain) so that users can still keep their own, but the internal company contact are managed. 
ie. If user no longer exists in GAL and is part of @mydomain.com remove.

I'm trying to sync to the main 'Contacts' folder so that it passes through to Teams and Outlook mobile apps etc. As it doesn't do it for additional contacts folders.

**Comment by Backmischung** [comment]
Hey there,
we´re experiencing the same. 
We wanted to assign all our employees phonenumbers (for signature reasons) but decided, that since they all are the same, we later wanted to remove those fields.
Now were stuck with the phonenumbers and they wont get removed.

the attribute phoneNumber correlates most likely to this line: 
`		if ($BusinssPhone -ne "")
		{
			$Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = $BusinssPhone
			`
			
i was wondering if the querry `if ($BusinssPhone -ne "" -Or NULL)` would work too?

also just as a sidenote: the variable is missing an "e" in $BusinssPhone but thats just an optic improvement. It works nontheless.

**Comment by grahamr975** [comment]
I did some digging into this. Unfortunately, deleting contact attributes using the EWS 2.0 API is an unnecessarily complicated process. I'll need to do some further research in order to find the correct Property IDs for each contact property that needs to be deletable.

https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/jj585538(v=exchg.80)

**Comment by Backmischung** [comment]
Hello again,

as a workaround, would it be possible to delete those NULL-attribute-contacts and simply sync them new?

My current plan is:
- hide my ~200 updated contacts from the GAL (by checking the hide from contactlist-box in our ECP)
- syncing contacts so they get deleted
- unchecking the box again so theyre shown again
- syncing to get the contacts back to everyone

Iill get you an update on how that worked.

**Comment by Backmischung** [comment]
Update: That didnt work as great as hoped.
The hidden contacts still got synced. 

Atleast to me, this behaviour doesn´t make sense.

Greetings

**Comment by grahamr975** [comment]
@nicolpas 

You can't set directly set a contact's property to null due to EWS silliness. Instead, you'd need to remove the extended property definition. If you're interested, there's documentation on this [here](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148?redirectedfrom=MSDN).

Try out the below code and let me know if this helps.

```
if ($BusinssPhone -eq "" -Or $BusinssPhone -eq $null) {
    $PidTagBusinessTelephoneNumber = new-object Microsoft.Exchange.WebServices.Data.ExtendedPropertyDefinition(0x3A08,[Microsoft.Exchange.WebServices.Data.MapiPropertyType]::String);
    $Contact.RemoveExtendedProperty($PidTagBusinessTelephoneNumber)
} else {
    $Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = $BusinssPhone
}
```

**Comment by nicolpas** [comment]
> @nicolpas
> 
> You can't set directly set a contact's property to null due to EWS silliness. Instead, you'd need to remove the extended property definition. If you're interested, there's documentation on this [here](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148?redirectedfrom=MSDN).
> 
> Try out the below code and let me know if this helps.
> 
> ```
> if ($BusinssPhone -eq "" -Or $BusinssPhone -eq $null) {
>     $PidTagBusinessTelephoneNumber = new-object Microsoft.Exchange.WebServices.Data.ExtendedPropertyDefinition(0x3A08,[Microsoft.Exchange.WebServices.Data.MapiPropertyType]::String);
>     $Contact.RemoveExtendedProperty($PidTagBusinessTelephoneNumber)
> } else {
>     $Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = $BusinssPhone
> }
> ```

Hi @grahamr975 and first of all many thanks for your reply.

I've try to modify only file Set-EXCContactObject.ps1 and I've replace:
`if ($BusinssPhone -ne "") { $Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = $BusinssPhone }`

with your code:

`if ($BusinssPhone -eq "" -Or $BusinssPhone -eq $null) {
    $PidTagBusinessTelephoneNumber = new-object Microsoft.Exchange.WebServices.Data.ExtendedPropertyDefinition(0x3A08,[Microsoft.Exchange.WebServices.Data.MapiPropertyType]::String);
    $Contact.RemoveExtendedProperty($PidTagBusinessTelephoneNumber)
} else {
    $Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = $BusinssPhone
}`

but Business phone still not emptied.

May be that:
- I've also to modify other files? I've see that also in file Set-EXCContact.ps1 there's same strings.
- that after $Contact.RemoveExtendedProperty($PidTagBusinessTelephoneNumber) I've to add a row to empty field BusinessPhone:
`$Contact.PhoneNumbers[[Microsoft.Exchange.WebServices.Data.PhoneNumberKey]::BusinessPhone] = ""`
?

**Comment by paochiz** [comment]
Hy Ryan any news on the topic :D

**Comment by christianneeb** [comment]
Any updates?

**Comment by Dark345** [comment]
> Update: That didnt work as great as hoped. The hidden contacts still got synced.
> 
> Atleast to me, this behaviour doesn´t make sense.
> 
> Greetings

@grahamr975 defintely we need to take care of this scenario

but, for the moment, workaround initially suggested by @Backmischung is working:

- Set the Hide from GAL for every mailbox (except one - $contactlist mustnot be null)
- Set $_.HiddenFromAddressListsEnabled -Match "True" in Get-Mailboxes.ps1
- Run script, it will delete contacts, since they are hidden from GAL
- Remove Hide from GAL for every mailbox
- Set $_.HiddenFromAddressListsEnabled -Match "False" in Get-Mailboxes.ps1
- Run script, it will create new updated contacts

**Comment by grahamr975** [comment]
With the latest commit, business and mobile phones can now be removed from contacts.
