### ISSUE TITLE
Contact photos (thumbnails) and address not shown in Business Cards

### ISSUE THREAD

**Issue by tipanic** [grahamr975/EWS-Office365-Contact-Sync#77]
Hello, thank you very much for this script, i just set it up initially and synced the contacts into one mailbox.

The Photos of all users are showing up, if i have the people view active, but when i switch to Business Card view , there are no photos shown in Outlook. Also the Address field is empty, while under people view its shown. When i open a contact and press "Update", the photo and address will show up.

Is there a way to fix this problem? I know that "Contact Sync" from NetSec has the exact same problem with O365 contacts.
When i manually copy the GAL into my contacts folder, all informations are shown in the Business Card view, but its not a convenient way for all users.

**Comment by grahamr975** [comment]
@tipanic

This script does not currently sync users' photos. Realistically, I won't add this feature anytime soon since including photos would drastically slow the speed of the sync. If you're up to the challenge, EWS does support this, as shown below.

https://social.msdn.microsoft.com/Forums/office/en-US/2e567ebe-c688-4d06-ae16-58f84f5f8ef0/setuserphoto-via-ews?forum=exchangesvrdevelopment
