### ISSUE TITLE
switches not syncing intended users

### ISSUE THREAD

**Issue by rypto** [grahamr975/EWS-Office365-Contact-Sync#78]
I've had this weird problem for a while now where I use the script with the **-ExcludeSharedMailboxContacts** and **-ExcludeContactsWithoutPhoneNumber** and only a portion of the users that suppose to get synced actually get synced.

When I compare two users in AD, one getting synced with another not getting synced, I can't seem to find any differences. They both are identical with the same attributes. What can I check? Please

**Comment by rypto** [comment]
Thanks Robs90 it seems to be it. I tried and changed the last part of the code on line 66 of Get-GAL-Contacts.ps1 as you provided in the other thread
`Where-Object {$EmailAddressList -Contains $.WindowsEmailAddress}`
 but I get errors when running the script. Did you encountered them too?
 
![image](https://user-images.githubusercontent.com/35531740/230100134-26ae182e-1356-410b-92ab-d717f49ecba9.png)

**Comment by Robs90** [comment]
No I did not, could it be that you changed the Filename of the Get-Calcontacts.ps1 File when editing it? Or maybe saved it as something else than a .ps1 File? 
If that´s the case, it doesn´t import it as a Function

**Comment by rypto** [comment]
no, just edited it, no filename changes. You only changed that last part and nothing else?

**Comment by Robs90** [comment]
To make this work, we did not change anything. Other changes were made, but only after testing this.

I did have this error when I added another Module to the Script (unrelated Changes), which turned out to be an error in the very first line of the .PS1 (the one starting with "function". ). In that case it turned out to be, that in that first line, the name of the function (Get-GALContacts in your case) was changed. Now these were errors I generated myself, but please verfify if the first line still looks like this:

_function Get-GALContacts {

**Comment by rypto** [comment]
It does...

**Comment by rypto** [comment]
Ok, so I tried with this line and it worked :-)
`| Where-Object {$EmailAddressList -contains $_.WindowsEmailAddress}`

**Comment by Robs90** [comment]
Thanks for the Feedback. Will check in my script and edit the post if needed, might have been an error just in my posted Code on Github.
