### ISSUE TITLE
Sync contacts to the default folder name. 

### ISSUE THREAD

**Issue by AhmedMahmoud87** [grahamr975/EWS-Office365-Contact-Sync#94]
is it possible to use the default contact folder instead of creating a new one ? I see the foldername parameter is mandatory.

**Comment by grahamr975** [comment]
Yes. You'll need to modify line 42 of the Folders/New-EXCContactFolder.ps1 function. I don't plan on implementing this as a feature since it would overwrite/delete any of the user's existing contacts, which would be a bad user experience.

**Old**
`Get-EXCContactFolder -SmptAddress $MailboxName -FolderPath "Contacts\$FolderName" -Service $service | Out-Null`
**New**
`Get-EXCContactFolder -SmptAddress $MailboxName -FolderPath "Contacts" -Service $service | Out-Null`
